### ISSUE TITLE
Vod 07/11/2022 does not load

### ISSUE THREAD

**Issue by loplw4** [OP-Archives/MOONMOON-site#15]
Vod title "[OMG] THIS GAME WAS banned on twitch????| followed by something else if we beat it early" continues to just load indefinitely. Vods before and after this one seem to be working just fine though. The vod is still there on youtube as well.

**Comment by TimIsOverpowered** [comment]
should be fixed 56e2586fa19861f98e730b43bd6838e875f85c18
