### ISSUE TITLE
Vod chat delay input doesn't let you enter negatives on iOS

### ISSUE THREAD

**Issue by ahmed176e** [OP-Archives/MOONMOON-site#17]
Kind of a small thing, but [this input](https://github.com/OP-Archives/MOONMOON-site/blob/56e2586fa19861f98e730b43bd6838e875f85c18/src/vods/Settings.js#L28) doesn't let you put in negative chat delays. Not sure exactly the right fix, but you can probably just add `type="number"` on the MUI TextInput component instead of setting the input prompts and it might do a better job?

![IMG_7947](https://github.com/OP-Archives/MOONMOON-site/assets/25637069/408df6bf-4dea-45a4-99b7-5ef7fbac805d)

**Comment by TimIsOverpowered** [comment]
c301a4674888c399e77509d95a389c2b5651535a
