### ISSUE TITLE
Comments not loading due to offset being NaN

### ISSUE THREAD

**Issue by bashenk** [OP-Archives/MOONMOON-site#18]
Comments are not loading due to some sort of calculation error. Modifying the value via the Playback Settings
UI does not fix the issue.
Manually visiting the archive.overpowered.tv URL shown below with a valid numerical value in place of the NaN returns proper results.

Stack trace
```
GET	https://archive.overpowered.tv/moonmoon/v1/vods/2150961390/comments?content_offset_seconds=NaN		500 (Internal Server Error)
(anonymous)	@	Chat.js:542
(anonymous)	@	Chat.js:580
setTimeout (async)		
(anonymous)	@	Chat.js:574
```

**Comment by TimIsOverpowered** [comment]
Thanks for the report. Should be fixed
