### ISSUE TITLE
Vods missing and stuttering - Latest 2 vods with giga issues (20231031 and 20231030)

### ISSUE THREAD

**Issue by vEXOULZ** [OP-Archives/MOONMOON-site#9]
## The latest 2 vods on moon2.tv have massive issues:

The following vods are missing huge chunks of stream:
- 20231030 - is missing a whole hour
- 20231031 - is missing basically the entire vod, it only has 1h and a half on moon2.tv

Although I haven't really watched the 31st stream vod, the 30th also has some major stutterings where video and audio freezes for about 5 seconds at a time

Some examples in 20231030 Part 2: (not an exhaustive list)
- ...
- 3:06 to 3:10
- 3:14 to 3:20
- 3:24 to 3:33
- 3:38 to 3:43
- ...
- 4:52 to 4:56
- 5:00 to 5:04
- 5:08 to 5:11
- 5:20 to 5:24
- ...
- 1:00:29 to 1:00:41
- ...

It mostly disappears if you skip forward to 1:30:00

## My completely uneducated hypothesis on what's happening:

The host server is dying (or crashing out) and keeps restarting or stuttering the vod recording in the process.

We can see a lot of partial vods on youtube that mostly accounts for the missing stream time on moon2.tv, but only the most recent vod (that didn't crash at the end?) gets posted on moon2.tv:

![image](https://github.com/TimIsOverpowered/MOONMOON-Frontend/assets/40424907/d9601e2a-740c-4e82-b164-e6be59ff2716)

**Comment by DaveYognaught** [comment]
We seem to be getting full vods again but the stuttering issue is still persisting. Even in the latest vod. 

1971444739

1:39:50 to 1:40:00
Then almost every other second from then on for several seconds at a time.

**Comment by TimIsOverpowered** [comment]
I'm monitoring the issue. Keep posting if it continues.

**Comment by Eeeee27** [comment]
Still an issue, as examples, lasts for several minutes in 
2009583508 ,  1:33:05

Only a minute or so in 
2015539400  ,  2:25:40
